# Generated by Django 2.1.5 on 2019-09-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiln',
            name='name',
            field=models.CharField(default='Kiln-1', max_length=10),
        ),
    ]
