# Generated by Django 2.1.5 on 2019-09-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_kiln_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='load',
            old_name='end',
            new_name='enddate',
        ),
        migrations.RenameField(
            model_name='load',
            old_name='start',
            new_name='startdate',
        ),
    ]
