# Generated by Django 2.1.5 on 2019-09-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190906_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='enddate',
            field=models.DateTimeField(blank=True),
        ),
    ]
