# Generated by Django 2.2.5 on 2019-09-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190906_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='loadnumber',
        ),
        migrations.AddField(
            model_name='load',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='kiln',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='kiln',
            name='name',
            field=models.CharField(default='Kiln-?', max_length=10),
        ),
    ]
