# Generated by Django 2.1.5 on 2019-09-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190906_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='fiber',
            field=models.FileField(blank=True, upload_to='uploaded_files/'),
        ),
    ]
