# Generated by Django 2.1.5 on 2019-09-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190906_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
